-- ============================================================
-- 015_zone_config_versions.sql
-- Auditability + rollback foundation for the zone configuration.
--
-- Each row is an immutable snapshot of the full staging_zones config at the
-- moment an admin clicks "Save Version" in the dashboard. This does NOT change
-- the live zone-save flow — it is an additive, append-only history table.
--
-- Non-destructive: CREATE TABLE IF NOT EXISTS + idempotent policies only.
-- Security: RLS enabled, admins may select/insert. No service role is used by
-- the frontend; writes come from the admin client under the admin's JWT.
-- Requires: 001_add_auth_columns.sql (is_admin()).
-- ============================================================

create table if not exists zone_config_versions (
  id             uuid        primary key default gen_random_uuid(),
  version_number bigint      generated by default as identity,
  snapshot       jsonb       not null,
  published_by   uuid        references drivers(id) on delete set null,
  published_at   timestamptz not null default now(),
  notes          text
);

-- Most-recent-first listing.
create index if not exists zone_config_versions_published_at_idx
  on zone_config_versions (published_at desc);

alter table zone_config_versions enable row level security;

drop policy if exists "zone versions admin read"   on zone_config_versions;
drop policy if exists "zone versions admin insert" on zone_config_versions;

-- Admins can read the full version history.
create policy "zone versions admin read"
  on zone_config_versions for select
  to authenticated
  using (is_admin(auth.uid()));

-- Admins can append new versions (writes come from the admin dashboard client).
create policy "zone versions admin insert"
  on zone_config_versions for insert
  to authenticated
  with check (is_admin(auth.uid()));
